### ISSUE TITLE
UIThreadException on Selecting Objects with Lasso Tool and Pressing D

### ISSUE THREAD

**Issue by jlogix** [pubpub-zz/ppInk#121]
07 / 13 / 2021 11:53UIThreadException

version 1.7.1.20789 built on 11/07/2021 11:32
Oops, ppInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

Index was outside the bounds of the array.

Stack Trace:
   at gInk.FormCollection.tiSlide_Tick(Object sender, EventArgs e) in D:\gink.git\ppInk\src\FormCollection.cs:line 4664
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by NOVAinc** [comment]
You beat me to this one! I'll attach a crash log as well
[crash.txt](https://github.com/pubpub-zz/ppInk/files/6810957/crash.txt)

**Comment by pubpub-zz** [comment]
This should fix.
[ppInk64_varFix13a.zip](https://github.com/pubpub-zz/ppInk/files/6811546/ppInk64_varFix13a.zip)

**Comment by NOVAinc** [comment]
I haven't encountered this issue anymore. Now it seems to be much more stable.

**Comment by pubpub-zz** [comment]
1.8 RC1 released
