### ISSUE TITLE
Issue while using shortkey to open the app + clicked anywhere

### ISSUE THREAD

**Issue by BlackBaron3** [pubpub-zz/ppInk#214]
Hi all,

I used the shortkey ctrl + D + alt to open the app and while pressing it I clicked anywhere and it returned this error. When clicking both, a big red arrow appears. I tried replicating but the crash doesn't occur again. Why is that?

---------------------------
UIThreadException
---------------------------
UIThreadException

version 1.8.3.19170 built on 15/08/2022 10:38

Oops, ppInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

Parameter is not valid.

Stack Trace:

   at System.Drawing.Image.get_Flags()

   at System.Windows.Forms.ControlPaint.IsImageTransparent(Image backgroundImage)

   at System.Windows.Forms.Control.PaintBackground(PaintEventArgs e, Rectangle rectangle, Color backColor, Point scrollOffset)

   at System.Windows.Forms.ButtonInternal.ButtonFlatAdapter.PaintBackground(PaintEventArgs e, Rectangle r, Color backColor)

   at System.Windows.Forms.ButtonInternal.ButtonFlatAdapter.PaintUp(PaintEventArgs e, CheckState state)

   at System.Windows.Forms.ButtonBase.OnPaint(PaintEventArgs pevent)

   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)

   at System.Windows.Forms.Control.WmPaint(Message& m)

   at System.Windows.Forms.Control.WndProc(Message& m)

   at System.Windows.Forms.ButtonBase.WndProc(Message& m)

   at System.Windows.Forms.Button.WndProc(Message& m)

   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

!!! Do you want to Quit ?
---------------------------
Yes   No   
---------------------------

**Comment by pubpub-zz** [comment]
Can you send the crash.txt in pink folder please

**Comment by BlackBaron3** [comment]
How can I do that?

**Comment by pubpub-zz** [comment]
go into ppink folder, select the 4 files I've indicated, press ctrl+C to copy them, go into your browser, in the issue and press ctrl+V to paste them

**Comment by pubpub-zz** [comment]
@BlackBaron3 any update ?

**Comment by pubpub-zz** [comment]
@BlackBaron3 any update (before closing)

**Comment by pubpub-zz** [comment]
without feedback I close this issue as solved. feel free to add a new comment to reopen it
