### ISSUE TITLE
Crashing when loading image from Clipboard

### ISSUE THREAD

**Issue by YouFoundJK** [pubpub-zz/ppInk#222]
Hey, @pubpub-zz, I'm using Windows 11 22H2. ppInk seems to crash everytime I try to load an image directly from clipboard. Below is the crash report.

--------------------------------------------------------------
11 - 16 - 2022 21:12UIThreadException

version 1.8.3.19170 built on 15/08/2022 10:38
Oops, ppInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

ClipBoard7633713 not loaded; prefer to use full path filename

Stack Trace:
   at gInk.ImageLister.getClipArtData(String fn, Int32 fill) in E:\ppink.src\ppInk\src\ImageLister.cs:line 253
   at gInk.FormCollection.btTool_Click(Object sender, EventArgs e) in E:\ppink.src\ppInk\src\FormCollection.cs:line 6317
   at gInk.FormCollection.tiSlide_Tick(Object sender, EventArgs e) in E:\ppink.src\ppInk\src\FormCollection.cs:line 5370
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

11 - 16 - 2022 22:08UIThreadException

version 1.8.3.19170 built on 15/08/2022 10:38
Oops, ppInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

ClipBoard7971951 not loaded; prefer to use full path filename

Stack Trace:
   at gInk.ImageLister.getClipArtData(String fn, Int32 fill) in E:\ppink.src\ppInk\src\ImageLister.cs:line 253
   at gInk.FormCollection.btTool_Click(Object sender, EventArgs e) in E:\ppink.src\ppInk\src\FormCollection.cs:line 6317
   at gInk.FormCollection.tiSlide_Tick(Object sender, EventArgs e) in E:\ppink.src\ppInk\src\FormCollection.cs:line 5370
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by pubpub-zz** [comment]
@YouFoundJK 
this could be linked from the image file format you are trying to paste
can you please provide the original image you are trying to paste?

**Comment by YouFoundJK** [comment]
I am not sure how to check that but does this help?

https://user-images.githubusercontent.com/72195985/202309008-ee01f64c-cea1-4242-a718-19e1be52b8d2.mp4

**Comment by pubpub-zz** [comment]
reproduced, under analysis

**Comment by pubpub-zz** [comment]
This should fix the issue can you confirm.
[ppink_Shift_fixClipboard.zip](https://github.com/pubpub-zz/ppInk/files/10034801/ppink_Shift_fixClipboard.zip)

I've also added a new feature where if you press shift in FreeHand, you will temporary enter line mode. cf #221

Give me your feed back

**Comment by YouFoundJK** [comment]
Heyy, sorry for the late reply. The clipboard and the new feature both work flawless now. Thanks a lot!
