### ISSUE TITLE
hardcoded D drive location

### ISSUE THREAD

**Issue by reseto** [pubpub-zz/ppInk#42]
UI Thread Exception when I exit ppink and start it again then hover over the image on bottom-right 
there's no drive D on this machine
content of crash.txt: 
```01 - 14 - 2021 15:14UIThreadException

version 1.4.1.23757 built on 11/01/2021 13:11
Oops, ppInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

C:/Users/rs/happy.png

Stack Trace:
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at System.Drawing.Image.FromFile(String filename)
   at gInk.ImageLister..ctor(Root rt) in D:\gink.git\ppInk\src\ImageLister.cs:line 40
   at gInk.FormCollection..ctor(Root root) in D:\gink.git\ppInk\src\FormCollection.cs:line 208
   at gInk.Root.StartInk() in D:\gink.git\ppInk\src\Root.cs:line 376
   at gInk.Root.callshortcut() in D:\gink.git\ppInk\src\Root.cs:line 323
   at gInk.CallForm._Click(Object sender, EventArgs e) in D:\gink.git\ppInk\src\CallForm.cs:line 27
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

01 - 14 - 2021 15:19UIThreadException

version 1.4.1.23757 built on 11/01/2021 13:11
Oops, ppInk crashed! Please include the following information if you plan to contact the developers (a copy of the following information is stored in crash.txt in the application folder):

C:/Users/rs/happy.png

Stack Trace:
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at System.Drawing.Image.FromFile(String filename)
   at gInk.ImageLister..ctor(Root rt) in D:\gink.git\ppInk\src\ImageLister.cs:line 40
   at gInk.FormCollection..ctor(Root root) in D:\gink.git\ppInk\src\FormCollection.cs:line 208
   at gInk.Root.StartInk() in D:\gink.git\ppInk\src\Root.cs:line 376
   at gInk.Root.callshortcut() in D:\gink.git\ppInk\src\Root.cs:line 323
   at gInk.CallForm._Click(Object sender, EventArgs e) in D:\gink.git\ppInk\src\CallForm.cs:line 27
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.Form.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

```

**Comment by pubpub-zz** [comment]
I'm sure your issue is linked with the D drive: the path indicated seems to more likely some debug info indicated the path of the original source file.
I understand that you copied the program in c:\users\rs folder . Did you copied there the whole folder including the images including happy.png file.

**Comment by pubpub-zz** [comment]
Hi @reseto,
Have you been able to review my latest comment. Do you have any update ? 
             Thx

**Comment by pubpub-zz** [comment]
Without any answer, I assume that you have solved your issue. If not, please reopen the issue with more details
